blank_issues_enabled: true
contact_links:
  - name: Bitcoin Core Security Policy
    url: https://github.com/bbcoin/bbcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Bitcoin Core Developers
    url: https://bbcoincore.org
    about: Bitcoin Core homepage
